version: "3.8"

services:
  app:
    build:
      context: .               # ВАЖНО: здесь лежат pom.xml, src, Dockerfile
      dockerfile: Dockerfile
    container_name: shorty_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: "put-strong-secret-here"   # замени на свой
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs       # опционально — логи на хост

  db:
    image: postgres:16
    container_name: shorty_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shorty
    ports:
      - "5450:5432"            # доступ из IDE: jdbc:postgresql://localhost:5450/shorty
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: shorty_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
