spring:
  datasource:
    url: jdbc:postgresql://db:5432/shorty
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.jdbc.batch_size: 100
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8080

jwt:
  # сам секрет берём из переменной окружения JWT_SECRET (в compose)
  expiration-seconds: 3600

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.security: INFO
    com.dmitry.shorty: INFO
