spring:
  datasource:
    url: jdbc:postgresql://localhost:5450/shorty
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.batch_size: 100
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
    enabled: true

server:
  port: 8080

jwt:
  secret: "7x!A%D*G-KaPdSgVkYp3s6v9y$B?E(H+MbQeThWmZq4t7w!z%C*F-J@NcRfUjXn2r"
  expiration-seconds: 3600

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.dmitry.shorty: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
  file:
    name: logs/application.log

debug: false