version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: shorty
      POSTGRES_USER: shorty
      POSTGRES_PASSWORD: shorty
    ports: ["5450:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]
volumes:
  dbdata: